---
# Install PostgreSQL on Enterprise Linux 6 (RHEL/CentOS/Scientific)
- hosts: localhost
  sudo: yes
  remote_user: root
  vars_files:
    - 'defaults/main.yml'
  tasks:
    - include: 'tasks/main.yml'
